ECard/Controllers/BannerController.cs
using Helpers;
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using ECard.DAL;
using ECard.Models;
using ECard.ViewModel;

namespace ECard.Controllers
{
    [Authorize]
    public class BannerController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();

        #region Banner
        public ActionResult ListBanner(int? page, int groupId = 0, string result = "")
        {
            ViewBag.Banner = result;
            var pageNumber = page ?? 1;
            const int pageSize = 10;
            var banners = _unitOfWork.BannerRepository.GetQuery(orderBy: q => q.OrderBy(a => a.GroupId).ThenBy(a => a.Sort));
            if (groupId > 0)
            {
                banners = banners.Where(a => a.GroupId == groupId);
            }
            var model = new ListBannerViewModel
            {
                Banners = banners.ToPagedList(pageNumber, pageSize),
            };
            return View(model);
        }
        public ActionResult Banner()
        {
            var model = new BannerViewModel()
            {
                Banner = new Banner() { Sort = 1, Active = true }
            };
            return View(model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Banner(BannerViewModel model, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                var isPost = true;
                var file = Request.Files["Banner.Image"];
                if (file != null && file.ContentLength > 0)
                {
                    if (!HtmlHelpers.CheckFileExt(file.FileName, "jpg|jpeg|png|gif|svg|mp4"))
                    {
                        ModelState.AddModelError("", @"Chỉ chấp nhận định dạng jpg, png, gif, jpeg, svg, mp4");
                        isPost = false;
                    }
                    else
                    {
                        if (file.ContentLength > 100000 * 1024)
                        {
                            ModelState.AddModelError("", @"Dung lượng lớn hơn 100MB. Hãy thử lại");
                            isPost = false;
                        }
                        else
                        {
                            var imgPath = "/images/banners/" + DateTime.Now.ToString("yyyy/MM/dd");
                            HtmlHelpers.CreateFolder(Server.MapPath(imgPath));

                            var imgFileName = HtmlHelpers.ConvertToUnSign(null, Path.GetFileNameWithoutExtension(file.FileName)) +
                                "-" + DateTime.Now.Millisecond + Path.GetExtension(file.FileName);

                            model.Banner.Image = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;
                            file.SaveAs(Server.MapPath(Path.Combine(imgPath, imgFileName)));
                        }
                    }
                }
                if (isPost)
                {
                    _unitOfWork.BannerRepository.Insert(model.Banner);
                    _unitOfWork.Save();

                    return RedirectToAction("ListBanner", new { result = "success" });
                }
            }
            return View(model);
        }
        public ActionResult EditBanner(int bannerId = 0)
        {
            var banner = _unitOfWork.BannerRepository.GetById(bannerId);
            if (banner == null)
            {
                return RedirectToAction("ListBanner");
            }
            var model = new BannerViewModel
            {
                Banner = banner,
            };
            return View(model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult EditBanner(BannerViewModel model, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                var isPost = true;

                var banner = _unitOfWork.BannerRepository.GetById(model.Banner.Id);

                var file = Request.Files["Banner.Image"];
                if (file != null && file.ContentLength > 0)
                {
                    if (!HtmlHelpers.CheckFileExt(file.FileName, "jpg|jpeg|png|gif|svg|mp4"))
                    {
                        ModelState.AddModelError("", @"Chỉ chấp nhận định dạng jpg, png, gif, jpeg, svg, mp4");
                        isPost = false;
                    }
                    else
                    {
                        if (file.ContentLength > 100000 * 1024)
                        {
                            ModelState.AddModelError("", @"Dung lượng lớn hơn 100MB. Hãy thử lại");
                            isPost = false;
                        }
                        else
                        {
                            var imgPath = "/images/banners/" + DateTime.Now.ToString("yyyy/MM/dd");
                            HtmlHelpers.CreateFolder(Server.MapPath(imgPath));
                            var imgFileName = HtmlHelpers.ConvertToUnSign(null, Path.GetFileNameWithoutExtension(file.FileName)) +
                                "-" + DateTime.Now.Millisecond + Path.GetExtension(file.FileName);

                            banner.Image = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;
                            file.SaveAs(Server.MapPath(Path.Combine(imgPath, imgFileName)));
                        }
                    }
                }

                if (isPost)
                {
                    banner.GroupId = model.Banner.GroupId;
                    banner.BannerName = model.Banner.BannerName;
                    banner.Slogan = model.Banner.Slogan;
                    banner.Sort = model.Banner.Sort;
                    banner.Active = model.Banner.Active;
                    banner.Url = model.Banner.Url;
                    banner.Content = model.Banner.Content;

                    _unitOfWork.BannerRepository.Update(banner);
                    _unitOfWork.Save();

                    return RedirectToAction("ListBanner", new { result = "update" });
                }
            }
            return View(model);
        }
        [HttpPost]
        public bool DeleteBanner(int bannerId = 0)
        {
            var banner = _unitOfWork.BannerRepository.GetById(bannerId);
            if (banner == null)
            {
                return false;
            }
            HtmlHelpers.DeleteFile(Server.MapPath("/images/banners/" + banner.Image));
            _unitOfWork.BannerRepository.Delete(banner);
            _unitOfWork.Save();
            return true;
        }
        public bool UpdateBannerQuick(int sort = 1, bool active = false, int bannerId = 0)
        {
            var banner = _unitOfWork.BannerRepository.GetById(bannerId);
            if (banner == null)
            {
                return false;
            }
            banner.Sort = sort;
            banner.Active = active;

            _unitOfWork.Save();
            return true;
        }
        #endregion
        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

ECard/Controllers/ContactController.cs
using Helpers;
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ECard.DAL;
using ECard.Models;
using ECard.ViewModel;
using System.Data.Entity;
using System.Runtime.InteropServices;
using Antlr.Runtime.Tree;

namespace ECard.Controllers
{
    [Authorize]
    public class ContactController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();

        #region Contact
        public ActionResult ListContact(int? page, string name)
        {
            var pageNumber = page ?? 1;
            const int pageSize = 15;
            var contact = _unitOfWork.ContactRepository.GetQuery(orderBy: l => l.OrderByDescending(a => a.Id));

            if (!string.IsNullOrEmpty(name))
            {
                contact = contact.Where(l => l.FullName.Contains(name));
            }
            var model = new ListContactViewModel
            {
                Contacts = contact.ToPagedList(pageNumber, pageSize),
                Name = name
            };
            return View(model);
        }
        [HttpPost]
        public bool DeleteContact(int contactId = 0)
        {
            var contact = _unitOfWork.ContactRepository.GetById(contactId);
            if (contact == null)
            {
                return false;
            }
            _unitOfWork.ContactRepository.Delete(contact);
            _unitOfWork.Save();
            return true;
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

ECard/Controllers/ProductVcmsController.cs
using ECard.DAL;
using ECard.Models;
using ECard.ViewModel;
using Helpers;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECard.Controllers
{
    [Authorize]
    public class ProductVcmsController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();

        #region Product  
        public ActionResult ListProduct(int? page, string name, string sort = "date-desc", string result = "")
        {
            ViewBag.Result = result;
            var pageNumber = page ?? 1;
            const int pageSize = 15;
            var products = _unitOfWork.ProductRepository.GetQuery().AsNoTracking();

            if (!string.IsNullOrEmpty(name))
            {
                products = products.Where(l => l.Name.Contains(name));
            }

            switch (sort)
            {
                case "sort-asc":
                    products = products.OrderBy(a => a.Sort);
                    break;
                case "sort-desc":
                    products = products.OrderByDescending(a => a.Sort);
                    break;
                case "hot":
                    products = products.OrderByDescending(a => a.Sort);
                    break;
                case "date-asc":
                    products = products.OrderBy(a => a.CreateDate);
                    break;
                default:
                    products = products.OrderByDescending(a => a.CreateDate);
                    break;
            }
            var model = new ListProductViewModel
            {
                Products = products.ToPagedList(pageNumber, pageSize),
                Name = name,
                Sort = sort
            };
            return View(model);
        }
        public ActionResult Product()
        {
            var model = new InsertProductViewModel
            {
                Product = new Product { Sort = 1, Active = true },
            };
            return View(model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Product(InsertProductViewModel model, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                model.Product.ListImage = fc["Pictures"];
                model.Product.Url = HtmlHelpers.ConvertToUnSign(null, model.Product.Url ?? model.Product.Name);

                var count = _unitOfWork.ProductRepository.GetQuery(a => a.Url == model.Product.Url).Count();
                if (count > 1)
                {
                    model.Product.Url += "-" + DateTime.Now.Millisecond;
                    _unitOfWork.Save();
                }

                _unitOfWork.ProductRepository.Insert(model.Product);
                _unitOfWork.Save();

                return RedirectToAction("ListProduct", new { result = "success" });
            }

            return View(model);
        }
        public ActionResult UpdateProduct(int proId = 0)
        {
            var product = _unitOfWork.ProductRepository.GetById(proId);
            if (product == null)
            {
                return RedirectToAction("ListProduct");
            }
            var model = new InsertProductViewModel
            {
                Product = product
            };
            return View(model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult UpdateProduct(InsertProductViewModel model, FormCollection fc)
        {
            var product = _unitOfWork.ProductRepository.GetById(model.Product.Id);
            if (product == null)
            {
                return RedirectToAction("ListProduct");
            }
            if (ModelState.IsValid)
            {
                product.ListImage = fc["Pictures"] == "" ? null : fc["Pictures"];
                product.Url = HtmlHelpers.ConvertToUnSign(null, model.Product.Url ?? model.Product.Name);
                product.Name = model.Product.Name;
                product.Body = model.Product.Body;
                product.Active = model.Product.Active;
                product.TitleMeta = model.Product.TitleMeta;
                product.DescriptionMeta = model.Product.DescriptionMeta;
                product.Sort = model.Product.Sort;

                _unitOfWork.Save();

                var count = _unitOfWork.ProductRepository.GetQuery(a => a.Url == product.Url).Count();
                if (count > 1)
                {
                    product.Url += "-" + DateTime.Now.Millisecond;
                    _unitOfWork.Save();
                }

                return RedirectToAction("ListProduct", new { result = "update" });
            }

            return View(model);
        }
        [HttpPost]
        public bool DeleteProduct(int proId = 0)
        {
            var product = _unitOfWork.ProductRepository.GetById(proId);
            if (product == null)
            {
                return false;
            }
            _unitOfWork.ProductRepository.Delete(product);
            _unitOfWork.Save();
            return true;
        }
        [HttpPost]
        public bool QuickUpdate(int? quantity, bool? status, bool active, int sort = 0, int proId = 0)
        {
            var product = _unitOfWork.ProductRepository.GetById(proId);
            if (product == null)
            {
                return false;
            }
            if (status != null)
            {
                product.Active = Convert.ToBoolean(status);
            }
            if (sort >= 0)
            {
                product.Sort = sort;
            }
            product.Active = active;
            _unitOfWork.Save();
            return true;
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

ECard/Views/Vcms/ChangePassword.cshtml
@model ECard.ViewModel.ChangePasswordModel
@{
    ViewBag.Title = "Đổi mật khẩu";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Thay đổi mật khẩu</h2>
@if (ViewBag.Result == 1)
{
    <div id="AlertBox" class="alert alert-success"><strong>Đổi mật khẩu thành công</strong></div>}
<a class="btn quick-link" href="@Url.Action("Index")"><i class="far fa-list mr-1"></i> Danh sách quản trị viên</a>
<div class="box_content px-300">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <table class="form_table">
            <tbody>
                <tr>
                    <td class="form_name">@Html.LabelFor(model => model.OldPassword)</td>
                    <td class="form_text">
                        @Html.PasswordFor(model => model.OldPassword, new { @class = "form_control w300" })
                        @Html.ValidationMessageFor(model => model.OldPassword)
                    </td>
                </tr>
                <tr>
                    <td class="form_name">@Html.LabelFor(model => model.Password)</td>
                    <td class="form_text">
                        @Html.PasswordFor(model => model.Password, new { @class = "form_control w300" })
                        @Html.ValidationMessageFor(model => model.Password)
                    </td>
                </tr>
                <tr>
                    <td class="form_name">@Html.LabelFor(model => model.ConfirmPassword)</td>
                    <td class="form_text">
                        @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form_control w300" })
                        @Html.ValidationMessageFor(model => model.ConfirmPassword)
                    </td>
                </tr>
                <tr>
                    <td class="form_name"></td>
                    <td class="form_text"><input class="btn quick-link" type="submit" value="Đổi mật khẩu"></td>
                </tr>
            </tbody>
        </table>}
</div>

ECard/Views/Vcms/ConfigSite.cshtml
@model ECard.Models.ConfigSite
@{
    ViewBag.Title = "Cấu hình Website";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .form_name {
        width: 135px;
    }
</style>
<a class="btn quick-link" href="@Url.Action("Index","Vcms")"><i class="far fa-list mr-1"></i> Quay lại trang chủ</a>
<div class="box_content">
    @if (ViewBag.Result == "success")
    {
        <div id="AlertBox" class="alert alert-success"><strong>Cập nhật thông tin thành công</strong></div>}
    @using (Html.BeginForm("ConfigSite", "Vcms", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(a => a.Id)
        <table class="form_table">
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Title)</td>
                <td class="form_text">@Html.EditorFor(model => model.Title)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Description)</td>
                <td class="form_text">@Html.EditorFor(model => model.Description)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Image)</td>
                <td class="form_text">@Html.TextBoxFor(model => model.Image, new { type = "file" }) <span class="red-warring">Kích thươc: 180px - 50px</span></td>
            </tr>
            @if (Model.Image != null)
            {
                <tr>
                    <td class="form_name"></td>
                    <td class="form_text"><img class="img-border" src="@Path.Combine("/images/configs/", Model.Image)?w=150" /></td>
                </tr>
            }
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Favicon)</td>
                <td class="form_text">@Html.TextBoxFor(model => model.Favicon, new { type = "file" }) <span class="red-warring">Kích thươc: 64px - 64px</span></td>
            </tr>
            @if (Model.Favicon != null)
            {
                <tr>
                    <td class="form_name"></td>
                    <td class="form_text"><img class="img-border" src="@Path.Combine("/images/configs/", Model.Favicon)?w=150" /></td>
                </tr>
            }
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.AboutText)</td>
                <td class="form_text">@Html.EditorFor(model => model.AboutText)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.InfoContact)</td>
                <td class="form_text">@Html.EditorFor(model => model.InfoContact)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.InfoFooter)</td>
                <td class="form_text">@Html.EditorFor(model => model.InfoFooter)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Place)</td>
                <td class="form_text">@Html.EditorFor(model => model.Place)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Hotline)</td>
                <td class="form_text">@Html.EditorFor(model => model.Hotline)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Zalo)</td>
                <td class="form_text">@Html.EditorFor(model => model.Zalo)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Email)</td>
                <td class="form_text">@Html.EditorFor(model => model.Email)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Facebook)</td>
                <td class="form_text">@Html.EditorFor(model => model.Facebook)</td>
            </tr>
            @*<tr>
                    <td class="form_name">@Html.LabelFor(model => model.Instagram)</td>
                    <td class="form_text">@Html.EditorFor(model => model.Instagram)</td>
                </tr>
                <tr>
                    <td class="form_name">@Html.LabelFor(model => model.Youtube)</td>
                    <td class="form_text">@Html.EditorFor(model => model.Youtube)</td>
                </tr>*@
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.GoogleMap)</td>
                <td class="form_text">@Html.EditorFor(model => model.GoogleMap)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.GoogleAnalytics)</td>
                <td class="form_text">@Html.EditorFor(model => model.GoogleAnalytics)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.LiveChat)</td>
                <td class="form_text">@Html.EditorFor(model => model.LiveChat)</td>
            </tr>
            <tr>
                <td class="form_name"></td>
                <td class="form_text"><input type="submit" class="btn quick-link" value="Cập nhật" /></td>
            </tr>
        </table>
    }
</div>

@section scripts{
    <script>
        $(function () {
            $("#ListImages").sortable();
            $("#ListImages").disableSelection();
        });
        var i = 1;
        $("#fileupload").fileupload({
            add: function (e, data) {
                var uploadErrors = [];
                var acceptFileTypes = /^image\/(gif|jpe?g|png)$/i;
                if (data.originalFiles[0]["type"].length && !acceptFileTypes.test(data.originalFiles[0]["type"])) {
                    uploadErrors.push("Chỉ chấp nhận định dạng jpeg, jpg, png, gif");
                }
                if (data.originalFiles[0]["size"] > 4000000) {
                    uploadErrors.push("Dung lượng ảnh lớn hơn 4MB");
                }
                var totalImg = $("#ListImages .thumb-img-box").length;
                if (totalImg >= 10) {
                    uploadErrors.push("Chỉ đăng tối đa 10 ảnh");
                }
                if (uploadErrors.length > 0) {
                    alert(uploadErrors.join("\n"));
                    return false;
                } else {
                    data.submit();
                }
                return true;
            },
            url: "/Uploader/Upload?folder=configs&r=" + Math.random(),
            dataType: "json",
            done: function (e, data) {
                $.each(data.result.files, function (index, file) {
                    $('#ListImages').append('<li><input type="hidden" name="Pictures" value ="' + file.name + '" /><img src="/images/configs/' + file.name + '?w=80&h=80"/><a href="javascript:;" id="' + i + '" onclick="delfile(' + i + ')"><img src="/content/admin/icon-delete.png" alt="" style="vertical-align:middle" /></a></li>');
                });
                i = i + 1;
                $("#progress").fadeOut(2000);
            },
            start: function () {
                $("#progress .progress-bar").css("width", "0");
                $("#progress").show();
            },
            progressall: function (e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);
                $("#progress .progress-bar").css("width", progress + "%");
            }
        }).prop('disabled', !$.support.fileInput).parent().addClass($.support.fileInput ? undefined : 'disabled');

        function delfile(divid) {
            if (confirm('Bạn có chắc xóa ảnh này?')) {
                $('#' + divid).parent().fadeOut().remove();
            }
        }
    </script>
}

ECard/Views/Vcms/CreateAdmin.cshtml
@model ECard.Models.Admin
@{
    ViewBag.Title = "Thêm quản trị";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@if (ViewBag.Result == "success")
{
    <div id="AlertBox" class="alert alert-success"><strong>Thêm mới admin thành công</strong></div>}
@if (ViewBag.Result == "update")
{
    <div id="AlertBox" class="alert alert-success"><strong>Cập nhật admin thành công</strong></div>}
<a class="btn quick-link" href="#list-admin"><i class="far fa-list mr-1"></i> Danh sách quản trị viên</a>
<div class="box_content px-300">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <table class="form_table">
            <tbody>
                <tr>
                    <td class="form_name">@Html.LabelFor(model => model.Username)</td>
                    <td class="form_text">
                        @Html.EditorFor(model => model.Username)
                    </td>
                </tr>
                <tr>
                    <td class="form_name">@Html.LabelFor(model => model.Password)</td>
                    <td class="form_text">
                        @Html.EditorFor(model => model.Password)
                    </td>
                </tr>
                <tr>
                    <td class="form_name">@Html.LabelFor(model => model.Active)</td>
                    <td class="form_text">@Html.CheckBoxFor(model => model.Active, new { @checked = "checked" })</td>
                </tr>
                <tr>
                    <td class="form_name"></td>
                    <td class="form_text">
                        <input type="submit" class="btn quick-link" value="Thêm mới">
                    </td>
                </tr>
            </tbody>
        </table>}
</div>
@Html.Action("ListAdmin", "Vcms")

ECard/Views/Vcms/EditAdmin.cshtml
@model ECard.ViewModel.EditAdminViewModel
@{
    ViewBag.Title = "Cập nhật quản trị";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<a class="btn quick-link" href="@Url.Action("CreateAdmin","Vcms")"><i class="far fa-list mr-1"></i> Danh sách quản trị viên</a>
<div class="box_content px-300">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        <table class="form_table">
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Username)</td>
                <td class="form_text">@Html.EditorFor(model => model.Username)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Password)</td>
                <td class="form_text">@Html.EditorFor(model => model.Password)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Active)</td>
                <td class="form_text">@Html.EditorFor(model => model.Active)</td>
            </tr>
            <tr>
                <td class="form_name"></td>
                <td class="form_text">
                    <input type="submit" class="btn quick-link" value="Cập nhật" />
                </td>
            </tr>
        </table>}
</div>
@Html.Action("ListAdmin", "Vcms")

ECard/Views/Vcms/Index.cshtml
@model ECard.ViewModel.InfoAdminViewModel
@{
    ViewBag.Title = "Welcome to website";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="top-title">
    <div class="media">
        <p><i class="fal fa-home-lg-alt"></i></p>
        <div class="media-body">
            <h5 class="mt-3">Tổng quan</h5>
        </div>
    </div>
    <div class="btn-group">
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="far fa-business-time mr-1"></i> Hòm thư
        </button>
        <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="@Url.Action("ListContact","Contact")"><i class="fal fa-envelope mr-1"></i> Hộp thư đến <span>@Model.Contacts</span></a>
        </div>
    </div>
</div>
<div class="row mt-4">
    <div class="col-sm-12 col-md-6 col-lg-3 mt-md-5 mt-3">
        <div class="overview-item">
            <div class="icon"><i class="fal fa-user"></i></div>
            <a class="stretched-link" href="@Url.Action("CreateAdmin","Vcms")">Quản trị viên</a>
            <p class="counter">@Model.Admins</p>
            <div class="info">
                <i class="far fa-edit mr-1"></i> Có thể thay đổi thông tin website
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-3 mt-md-5 mt-3">
        <div class="overview-item">
            <div class="icon icon-product"><i class="fal fa-box"></i></div>
            <a class="stretched-link" href="@Url.Action("ListProduct","ProductVcms")">Sản phẩm</a>
            <p class="counter">@Model.Products</p>
            <div class="info">
                <i class="fal fa-shopping-cart mr-1"></i> Cập nhật liên tục
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-3 mt-md-5 mt-3">
        <div class="overview-item">
            <div class="icon icon-article"> <i class="fal fa-newspaper"></i></div>
            <a class="stretched-link" href="@Url.Action("ListArticle","Article")">Tin tức</a>
            <p class="counter">@Model.Articles</p>
            <div class="info">
                <i class="far fa-history mr-1"></i> Tin tức mới nhất
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-3 mt-md-5 mt-3">
        <div class="overview-item">
            <div class="icon icon-cart"><i class="fal fa-ad mr-1"></i></div>
            <a class="stretched-link" href="@Url.Action("ListBanner","Banner")">Quảng cáo</a>
            <p class="counter">@Model.Banners</p>
            <div class="info">
                <i class="far fa-history mr-1"></i> Cập nhật liên tục
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-3 mt-md-5 mt-3">
        <div class="overview-item">
            <div class="icon icon-city"><i class="fal fa-mailbox"></i></div>
            <a class="stretched-link" href="@Url.Action("ListContact","Contact")">Liên hệ</a>
            <p class="counter">@Model.Contacts</p>
            <div class="info">
                <i class="far fa-history mr-1"></i> Cập nhật mới nhất
            </div>
        </div>
    </div>
</div>